<% project_name = 'pharmacy-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: pharmacy_api_development

test:
  <<: *default
  database: pharmacy_api_test
